site_name: rv32emc 

theme: 
    name: material
    features:
        - toc.integrate
        - navigation.top
    icon:
        repo: fontawesome/brands/github

use_directory_urls: false

markdown_extensions:
    - mdx_math  
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets    
    - pymdownx.arithmatex:
        generic: true
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html
    - tables
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - toc:
        permalink: true

extra_javascript:     
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/shin-yamashita/rv32emc

repo_name: shin-yamashita/rv32emc

edit_uri: ""

